### ISSUE TITLE
Enable http/2 when available 

### ISSUE THREAD

**Issue by HansEJC** [HansEJC/hansejc.github.io#9]
https://www.lighttpd.net/2020/11/29/1.4.56/ 

only applies to hansejc.ddns.net

**Comment by gstrauss** [comment]
HTTP/2 is enabled by default in lighttpd 1.4.59

**Comment by HansEJC** [comment]
Not ready yet [Entware Github](https://github.com/Entware/Entware/issues/616).

**Comment by HansEJC** [comment]
> HTTP/2 is enabled by default in lighttpd 1.4.59

Sorry, I hadn't realised making this issue would notify other people, I'm new to Github. Yes, I have seen that it is available on lighttpd now, but I can't install it on my router yet. Just waiting for it to be available on Entware. 

Thanks for your work on lighttpd, it works great!
